### PR TITLE
Set different expectation keys for pod and service

### LINKED ISSUE #78: Expectation is incorrectly configured
We use `GenExpectationPodsKey` in both `onDependentCreateFunc` and `onDependentDeleteFunc`. 

https://github.com/kubeflow/xgboost-operator/blob/5f016324147205203670fa3fb46967afa0740756/pkg/controller/xgboostjob/expectation.go#L65

https://github.com/kubeflow/xgboost-operator/blob/5f016324147205203670fa3fb46967afa0740756/pkg/controller/xgboostjob/expectation.go#L89

However, PodWatch and ServiceWatch both use them as predicate functions. 

https://github.com/kubeflow/xgboost-operator/blob/5f016324147205203670fa3fb46967afa0740756/pkg/controller/xgboostjob/xgboostjob_controller.go#L162

Currently, it doesn't surface problems under normal cases since pod and headless service are created as a pair.  But this is still a bug we need to fix.

### PR DESCRIPTION
**Pull request by Jeffwan**
resolve #78 

Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>

### CODE REVIEW

File: pkg/controller/xgboostjob/expectation.go [hunk 1]
```diff
@@ -62,7 +63,14 @@ func onDependentCreateFunc(r reconcile.Reconciler) func(event.CreateEvent) bool
 
 		logrus.Info("Update on create function ", xgbr.ControllerName(), " create object ", e.Meta.GetName())
 		if controllerRef := metav1.GetControllerOf(e.Meta); controllerRef != nil {
-			expectKey := job_controller.GenExpectationPodsKey(e.Meta.GetNamespace()+"/"+controllerRef.Name, rtype)
+			var expectKey string
+			if _, ok := e.Object.(*corev1.Pod); ok {
+				expectKey = job_controller.GenExpectationPodsKey(e.Meta.GetNamespace()+"/"+controllerRef.Name, rtype)
```
Comment (terrytangyuan) [inline pkg/controller/xgboostjob/expectation.go:68]: Move `e.Meta.GetNamespace()+"/"+controllerRef.Name` to a variable that can be reused?

Comment (Jeffwan) [reply pkg/controller/xgboostjob/expectation.go:68]: Yeah, sounds good. I will update it
